export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const ACCOUNT_LOGIN_STATUS_CHANGED = 'ACCOUNT_LOGIN_STATUS_CHANGED';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';

export const CATEGORY_GET_LISTS_SUCCESS = 'CATEGORY_GET_LISTS_SUCCESS';
export const CATEGORY_GET_ENTITY_SUCCESS = 'CATEGORY_GET_ENTITY_SUCCESS';

export const TOPIC_GET_LISTS_SUCCESS = 'TOPIC_GET_LISTS_SUCCESS';
export const TOPIC_GET_ENTITY_SUCCESS = 'TOPIC_GET_ENTITY_SUCCESS';

export const ARTICLE_GET_LISTS_SUCCESS = 'ARTICLE_GET_LISTS_SUCCESS';
export const ARTICLE_GET_ENTITY_SUCCESS = 'ARTICLE_GET_ENTITY_SUCCESS';

export const TAG_GET_LISTS_SUCCESS = 'TAG_GET_LISTS_SUCCESS';
export const TAG_GET_ENTITY_SUCCESS = 'TAG_GET_ENTITY_SUCCESS';
