export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const HOME_MASTHEAD_GET_ENTITY_SUCCESS = 'HOME_MASTHEAD_GET_ENTITY_SUCCESS';
export const HOME_MOTTO_GET_ENTITY_SUCCESS = 'HOME_MOTTO_GET_ENTITY_SUCCESS';
export const HOME_SIDE_TAG_GET_LISTS_SUCCESS = 'HOME_SIDE_TAG_GET_LISTS_SUCCESS';
export const HOME_SIDE_LINK_GET_LISTS_SUCCESS = 'HOME_SIDE_LINK_GET_LISTS_SUCCESS';

export const ACCOUNT_LOGIN_STATUS_CHANGED = 'ACCOUNT_LOGIN_STATUS_CHANGED';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';

export const TOPIC_GET_LISTS_SUCCESS = 'TOPIC_GET_LISTS_SUCCESS';
export const TOPIC_GET_ENTITY_SUCCESS = 'TOPIC_GET_ENTITY_SUCCESS';

export const ARTICLE_GET_LISTS_SUCCESS = 'ARTICLE_GET_LISTS_SUCCESS';
export const ARTICLE_GET_ENTITY_SUCCESS = 'ARTICLE_GET_ENTITY_SUCCESS';
